/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UniValid {
    'config': any;
    'key': string;
  }
  interface UniValidAttributes extends StencilHTMLAttributes {
    'config'?: any;
    'key'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UniValid': Components.UniValid;
  }

  interface StencilIntrinsicElements {
    'uni-valid': Components.UniValidAttributes;
  }


  interface HTMLUniValidElement extends Components.UniValid, HTMLStencilElement {}
  var HTMLUniValidElement: {
    prototype: HTMLUniValidElement;
    new (): HTMLUniValidElement;
  };

  interface HTMLElementTagNameMap {
    'uni-valid': HTMLUniValidElement
  }

  interface ElementTagNameMap {
    'uni-valid': HTMLUniValidElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
